# Generated by Django 3.0.6 on 2020-05-17 11:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('phones', '0001_initial'), ('phones', '0002_auto_20200517_1127')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=200, unique=True)),
                ('create_date', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='date published')),
            ],
        ),
    ]
